version: "3"
services:
  nats:
    image: noxecane/nats-js-image
    expose:
      - 4222
    ports:
      - "4222:4222"
    restart: "on-failure"
  streamer:
      build:
        context: "../"
        dockerfile: "Dockerfile"
      depends_on:
        - nats
      environment:
        NATS_URI: "nats://nats:4222"
        STREAMS: "transactions,wallets"